# Generated by Django 6.0.7 on 2026-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_candle'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='quote_volume',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='candle',
            name='taker_buy_base_volume',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='candle',
            name='taker_buy_quote_volume',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='candle',
            name='trades',
            field=models.IntegerField(default=0),
        ),
    ]
