# Generated by Django 6.0.7 on 2026-07-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_candle_quote_volume_candle_taker_buy_base_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=10)),
                ('open_interest', models.DecimalField(decimal_places=8, max_digits=30)),
                ('open_interest_value', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('timestamp', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_interest', to='market_data.coin')),
            ],
            options={
                'unique_together': {('coin', 'timeframe', 'timestamp')},
            },
        ),
    ]
