# Generated by Django 6.0.7 on 2026-07-17 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_openinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('mark_price', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('funding_time', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rates', to='market_data.coin')),
            ],
            options={
                'unique_together': {('coin', 'funding_time')},
            },
        ),
    ]
