# Generated by Django 6.0.7 on 2026-07-17 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0005_fundingrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('index_price', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('estimated_settle_price', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('funding_rate', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('next_funding_time', models.BigIntegerField(default=0)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_prices', to='market_data.coin')),
            ],
            options={
                'unique_together': {('coin', 'timestamp')},
            },
        ),
    ]
