# Generated by Django 6.0.7 on 2026-07-17 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0007_longshortratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopTraderRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=10)),
                ('long_short_ratio', models.DecimalField(decimal_places=8, max_digits=20)),
                ('long_account', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('short_account', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('timestamp', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_trader_ratios', to='market_data.coin')),
            ],
            options={
                'unique_together': {('coin', 'timeframe', 'timestamp')},
            },
        ),
    ]
